### ISSUE TITLE
'Motion'  causes issues w/ WMR, and seated experiences (roomcenter issues as well). (workingsetpreview issues)

### ISSUE THREAD

**Issue by reidm** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#170]
I'm experiencing the same issue as #145 , running 3.1.0. I'm using a Samsung Odyssey (original), Steam VR beta, and Windows MR for Steam beta.

The problem is the same, the 'recenter HMD' function in both Elite Dangerous and iRacing doesn't work. What appears to happen is that the view recenters to the desired position for a split second, and then the view returns to the original undesired position, as if the button was not pressed.

Checking the 'Allow External App Chaperone Edits' option does not affect the behaviour.

I see the same issue with 3.1.0, and also the test build linked in #145.  It seems that the fix  #150 doesn't work for my hardware for some reason. Reverting to 2.8 resolves the issue.

**Comment by reidm** [comment]
Also, with 3.1.0 when seeing this issue, the up/down head movement loses tracking. Side to side and forwards/backwards still track fine.

**Comment by Kung-vr** [comment]
[This build](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23387574/job/x891t38ixkug1dbi/artifacts) is an old (more aggressive) attempt at fixing the issue. Could you see if it fixes the motion for you? I wouldn't recommend running the build long term, but if this fixes it'll help pinpoint the issue. Btw if this version is old enough that it still has the undo button in space fix, don't click it... might misalign stuff. This is only for the snap back on release of motion binds problem. This build doesn't fix seated mode.

**Comment by reidm** [comment]
Yes, that build works fine for me. 'Recenter HMD' works, and z tracking works.

**Comment by Kung-vr** [comment]
I think more stuff is working there than should be... hmm. Glad it works, but might be something going on with swapping versions. Could you pastebin your log file? Logfile is at C:\Users\Username\AppData\Roaming\AdvancedSettings-Team\AdvancedSettings.log on windows.

**Comment by reidm** [comment]
Yes, here it is: [log](https://pastebin.com/zbba4F5p)

**Comment by Kung-vr** [comment]
Could you give [this build](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23998008/job/61fgwyd3b6bq7kje/artifacts) a try, and enable the "Old-Style Motion" option in the settings tab?

**Comment by reidm** [comment]
Unfortunately that has the same problems (reset doesn't work, no z tracking). [log](https://pastebin.com/RsiJQ9Ef)

**Comment by Kung-vr** [comment]
Could you attempt this trouble-shooting sequence?

1. Make sure the Old-Style Motion option is checked and then quit out of everything and do a full system reboot.
2. Start Steamvr manually first (don't launch your game to have it auto-start steamvr)
3. After Steamvr is properly booted up, load one of the games you've been having trouble with.
4. As well as the game's own recenter bind, try clicking the "Seated Recenter" button on the bottom right of the offsets tab. (This button will become visible when you're in a seated mode game)
5. Also try pressing the +/- buttons on the offsets in the offsets tab to see if this does anything.
6. Post log and report findings

Thanks for your continued testing.

**Comment by reidm** [comment]
Still seeing the same issue following those steps. [Log](https://pastebin.com/QuePgPdB)

In the offsets tab, when pressing either the in game button, or 'seated recenter' in Advanced settings, the X/Z numbers, and rotation numbers change, and it looks like they accurately reflect where the offset should be. But, the in game view doesn't reflect these numbers. Clicking +/- only change the numbers in the box as well.

Happy to help!

**Comment by ykeara** [comment]
Okay Probably not a good solution for you, but you need to "set me up for all experiences", and have the WMR boundary on.... This should fix the issues.... you can turn the boundary off once steamVR is loaded... but it always needs to be on before SteamVR launches otherwise it will cause issues... looking into A better "fix" but that is work-around for now.

**Comment by reidm** [comment]
Interesting. That does work with the latest test build above. Even with the 'external chaperone' and 'old style motion' options disabled. No problem recentering my view, and I maintained full tracking.

When I launch WMR, the option to disable the boundary is grayed out. It is enabled once the headset figures out where it is, then 6DoF is enabled, other wise there is no transnational tracking. I have always followed: wait until that option was available (so I know I have tracking), then disable boundary, then sit down.

**Comment by ykeara** [comment]
ye... it may not be fixable from our (openVR) end.... as its kinda  a WMR thing.... I probably should look into someone to contact over there.

**Comment by reidm** [comment]
It wouldn't hurt. I bought this thing on day 1 just because of the sweet screens. The software was pretty hurting when it was released, but MS has clearly put a bunch of effort into it, including Steam integration. I think they are responsive to input. They were the first ones to do the inside out stuff. OpenVR may not have even really supported it to begin with, so they probably have some oddities related to that.

I appreciate everyone that has looked into this, thank you.

**Comment by bubbabushido** [comment]
I am also having this problem, but the 3.0 build posted did not fix it on my system. Reverting to 2.8 fixed it, but 2.8 is lacking the motion settings I need for other games.

**Comment by ykeara** [comment]
Closing Issue:

Will Add to documentation for a requirement for WMR users to be set-up w/ bounds on.

Again if you are having issues set up WMR for all experiences and bounds must be on when starting SteamVR. This appears to be an Issue on WMR's end, and we have reached out to MSFT team to see if intentional or a bug on their end.

**Comment by deinlandel** [comment]
I have the same bug with Pimax and Advanced Settings 3.1.0. Pimax uses SteamVR and even SteamVR chaperone.

"What appears to happen is that the view recenters to the desired position for a split second, and then the view returns to the original undesired position, as if the button was not pressed"

This happens in seated apps, for example DeoVR player or Whirligig

**Comment by ykeara** [comment]
@deinlandel Are you set-up as standing only or room-scale?

**Comment by ykeara** [comment]
Rolling other issues Into this one as a catch-all for motion issues, specifically those around WMR and possibly even LH based systems in "standing only" or some seated games.

**Comment by Kung-vr** [comment]
I've referenced this in the pull request above, but this still may require more debugging (even though it's improved) So I'm leaving the issue open for now.

**Comment by ykeara** [comment]
Closing should be fixed per #298
